<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3-sd:src/main/webapp/WEB-INF/sitemesh/minimal.p.vm.jsp
--%>
<%@ taglib uri="http://www.opensymphony.com/sitemesh/decorator" prefix="decorator"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<jsp:useBean id="sysProp" class="com.iisigroup.cap.base.CapSystemProperties" scope="application" />
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="${sysProp['context_path']}/static/css/main.css" />
<link rel="stylesheet" href="${sysProp['context_path']}/static/css/form.css" />
<link rel="stylesheet" href="${sysProp['context_path']}/static/lib/css/common.message.css" />
<!-- common.message (iLog) -->
<!--[if lt IE 9]>
            <script src="${sysProp['context_path']}/static/lib/js/html5.js"></script>
        <![endif]-->
<script type="text/javascript">
  var baseUrl = "${sysProp['context_path']}/static";
</script>
<title><decorator:title default="CapWebMVC" /></title>
<script src="${sysProp['context_path']}/static/requirejs/2.3.2/require.min.js"></script>
<script src="${sysProp['context_path']}/static/main.js"></script>
<decorator:getProperty property="reqJSON" default="" />
<decorator:getProperty property="i18n" default="" />
<decorator:head />
</head>
<body>
    <div class="mainBody">
        <div class="logo">
            <a><img src="${sysProp['context_path']}/static/images/mb-logo.png"></a>
            <div>Icons made by <a href="https://www.flaticon.com/authors/gregor-cresnar" title="Gregor Cresnar">Gregor Cresnar</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
        </div>
        <div class="main">
            <decorator:body />
        </div>
        <div class="clear"></div>
        <footer>
            <div class="copyright">資拓宏宇國際股份有限公司 © 2012 版權所有</div>
        </footer>
        <div class="bg-around right">&nbsp;</div>
        <div class="bg-around left">&nbsp;</div>
    </div>
</body>
</html>
